-- Per-account lockout after repeated failed sign-ins.
--
-- Hand-written rather than generated by `migrate dev`, for the same reason as
-- every migration before it: this project connects through Neon's pooled
-- endpoint, where Prisma cannot build the shadow database its drift detection
-- needs, so `migrate dev` misreads the postgis extension as drift and offers to
-- reset. Apply with `prisma migrate deploy`.
--
-- Purely additive, and safe against existing rows:
--
--  * `failedLoginAttempts` is NOT NULL with a default, so the ~21 existing users
--    get 0 without a table rewrite of their own.
--  * `lockedUntil` is nullable, which is what "not locked" means. No backfill.
--
-- No index. Both columns are only ever read via a lookup that already has the
-- user by primary key or unique email — there is no query that searches *for*
-- locked accounts. Add one if an admin screen ever lists them.

-- AlterTable
ALTER TABLE "User"
  ADD COLUMN "failedLoginAttempts" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "lockedUntil" TIMESTAMP(3);
