-- Append-only audit trail.
--
-- Hand-written rather than generated by `migrate dev`, for the same reason as
-- the previous migrations: this project connects through Neon's pooled
-- endpoint, where Prisma cannot build the shadow database its drift detection
-- needs, so `migrate dev` misreads the postgis extension as drift and offers to
-- reset. Apply with `prisma migrate deploy`.
--
-- Purely additive: a new table and its index. Nothing existing is touched.
--
-- Two things about this table that are not obvious from the DDL:
--
--  * `actorName`, `actorRole` and `targetLabel` are denormalised on purpose.
--    People get renamed, change role and leave; resolving those at read time
--    would make an old entry describe today's org chart rather than what
--    actually happened.
--  * Nothing deletes from here. TokenCleanupService sweeps the four token
--    tables only, and there is no update or delete path in the code. Audit rows
--    should outlive the records they describe — keep them as long as the
--    payroll data they explain.

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "actorId" TEXT,
    "actorName" TEXT NOT NULL,
    "actorRole" "UserRole",
    "action" TEXT NOT NULL,
    "targetType" TEXT,
    "targetId" TEXT,
    "targetLabel" TEXT,
    "ipAddress" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
-- Every read is "this organization's entries, newest first".
CREATE INDEX "AuditLog_organizationId_createdAt_idx" ON "AuditLog"("organizationId", "createdAt");

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
