-- Let two companies share a name.
--
-- Hand-written rather than generated by `migrate dev`, for the same reason as
-- the previous four migrations: this project connects through Neon's pooled
-- endpoint, where Prisma cannot build the shadow database its drift detection
-- needs, so `migrate dev` misreads the postgis extension as drift and offers to
-- reset. Apply with `prisma migrate deploy`.
--
-- Safe on existing data: this RELAXES a constraint. Every row that satisfied
-- "organization names are unique" still satisfies "they need not be", so
-- nothing can fail validation and nothing is rewritten.
--
-- No replacement index, unlike the ActivationToken.userId change. That one
-- dropped a UNIQUE that was carrying real lookups; nothing queries Organization
-- by name — tenants are addressed by id, and sign-in is by email or employee
-- ID. Adding an index here would cost writes and serve nothing.

-- DropIndex
DROP INDEX "Organization_name_key";
