-- Allow more than one activation token per user, so an invitation can be re-sent.
--
-- Hand-written rather than generated by `migrate dev`, for the same reason as
-- the previous two migrations: this project connects through Neon's pooled
-- endpoint, where Prisma cannot build the shadow database its drift detection
-- needs, so `migrate dev` misreads the postgis extension as drift and offers to
-- reset. Apply with `prisma migrate deploy`. The SQL below is exactly what
-- `prisma migrate diff` produced.
--
-- Safe on existing data: this RELAXES a constraint. Every row that satisfied
-- "one activation token per user" still satisfies "any number per user", so
-- nothing can fail validation and nothing is rewritten.
--
-- The replacement index is not optional. The dropped UNIQUE was providing the
-- index behind every lookup by userId and behind the delete cascade; without
-- it those become sequential scans of a table that now grows with every invite.

-- DropIndex
DROP INDEX "ActivationToken_userId_key";

-- CreateIndex
CREATE INDEX "ActivationToken_userId_idx" ON "ActivationToken"("userId");
