-- Refresh-token families (theft detection) and the foreign-key indexes.
--
-- Hand-written rather than generated by `migrate dev`: this project connects
-- through Neon's pooled endpoint, where Prisma cannot build the shadow database
-- its drift detection needs, so `migrate dev` misreads the postgis extension as
-- drift and offers to reset. Apply with `prisma migrate deploy`, which does no
-- drift detection. The SQL below is exactly what `prisma migrate diff` produced.

-- Existing refresh tokens cannot be given a familyId. A family identifies a
-- CHAIN OF ROTATIONS descending from one sign-in, and rows written before this
-- migration have no chain to belong to — there is no correct value to backfill,
-- and inventing one would make unrelated tokens look like the same session,
-- which is exactly what the theft detection reads.
--
-- Clearing them is safe: refresh tokens are disposable by design, nothing else
-- references these rows, and the entire cost is that anyone currently signed in
-- signs in once more. This must come first, or the NOT NULL column below fails
-- against the existing rows.
DELETE FROM "RefreshToken";

-- AlterTable
ALTER TABLE "RefreshToken" ADD COLUMN     "familyId" TEXT NOT NULL,
ADD COLUMN     "rotatedAt" TIMESTAMP(3);

-- CreateIndex
CREATE INDEX "PasswordResetToken_userId_idx" ON "PasswordResetToken"("userId");

-- CreateIndex
CREATE INDEX "RefreshToken_userId_idx" ON "RefreshToken"("userId");

-- CreateIndex
CREATE INDEX "RefreshToken_familyId_idx" ON "RefreshToken"("familyId");

-- CreateIndex
CREATE INDEX "User_organizationId_idx" ON "User"("organizationId");

-- CreateIndex
CREATE INDEX "User_departmentId_idx" ON "User"("departmentId");

-- CreateIndex
CREATE INDEX "User_officeId_idx" ON "User"("officeId");
