-- Soft delete for users.
--
-- Hand-written rather than generated by `migrate dev`, for the same reason as
-- 20260910120000: this project connects through Neon's pooled endpoint, where
-- Prisma cannot build the shadow database its drift detection needs, so
-- `migrate dev` misreads the postgis extension as drift and offers to reset.
-- Apply with `prisma migrate deploy`, which does no drift detection. The SQL
-- below is exactly what `prisma migrate diff` produced.
--
-- Purely additive: no data is deleted, nothing becomes NOT NULL, and existing
-- rows keep their current status with deletedAt left null.

-- AlterEnum
ALTER TYPE "UserStatus" ADD VALUE 'DELETED';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "deletedAt" TIMESTAMP(3);
